FROM mcr.microsoft.com/devcontainers/base:2.0.4-noble
RUN apt-get update && apt-get install -y python3.11 python3-pip python3.11-venv
RUN ln -sf /usr/bin/python3.11 /usr/bin/python3
RUN ln -sf /usr/bin/pip3 /usr/bin/pip
